### ISSUE TITLE
Test suite doesn't use pytest idioms

### ISSUE THREAD

**Issue by kevinsa5** [ajakef/gemlog#11]
PyTest has lots of bells and whistles to write elegant test functions.  For example, this toy function:

```python
def test_function():
    "test the thing"
    try:
        1/0
    except ZeroDivisionError:
        print("Raises correct error")
    except:
        raise Exception("Raises wrong error")
    else:
        raise Exception("Doesn't raise any error!")
```

is more idiomatically written using the [pytest.raises](https://docs.pytest.org/en/stable/reference.html#pytest-raises) context manager:

```python
import pytest

def test_function():
    "test the thing"
    with pytest.raises(ZeroDivisionError):
        1/0
```

I also suggest putting test files in a `tests` folder to keep things tidier.  Having the test files alongside the module files means python thinks you might want to import them:

![image](https://user-images.githubusercontent.com/57452607/92064153-26156f80-ed5a-11ea-94ab-46c0eb723f17.png)

**Comment by ajakef** [comment]
[Done](https://github.com/ajakef/gemlog/commit/13e9b7386a762ea921ed75087da725dae4301478), thanks.
