### ISSUE TITLE
Issue converting demo data

### ISSUE THREAD

**Issue by fkdannemann** [ajakef/gemlog#29]
Running into the issue below when running the demo:

```
inputdir  raw
serial numbers  ['077', '088', '096', '103', '106', '109']
outputdir  mseed
No non-corrupt data files for SN "077" found in raw directory raw
No non-corrupt data files for SN "088" found in raw directory raw
No non-corrupt data files for SN "096" found in raw directory raw
No non-corrupt data files for SN "103" found in raw directory raw
No non-corrupt data files for SN "106" found in raw directory raw
No non-corrupt data files for SN "109" found in raw directory raw
```

**Comment by ajakef** [comment]
Just ran that command from the demo and it works for me. I'm using the current version 1.4.3; could you please run 'gemconvert -h' and paste in the version number? And, run 'ls -lh raw' and verify that the file sizes are approximately correct?
-rw-r--r-- 1 jake jake 6981355 Sep 14  2020 FILE0010.096
-rw-r--r-- 1 jake jake 6975098 Sep 14  2020 FILE0010.103
-rw-r--r-- 1 jake jake 6985595 Sep 14  2020 FILE0010.109
-rw-r--r-- 1 jake jake 6977047 Sep 14  2020 FILE0011.088
-rw-r--r-- 1 jake jake 6976499 Sep 14  2020 FILE0011.106
-rw-r--r-- 1 jake jake 6665075 Sep 14  2020 FILE0012.077

**Comment by fkdannemann** [comment]
Version number looks the same, I am getting 6.7M for the file sizes which is probably the problem.

**Comment by ajakef** [comment]
Oops, I told you 'ls -lh' but the output I printed was for 'ls -l'. 6.7M is the correct file size. Could you run the following?
rm gemconvert_logfile.txt # start with a fresh log file
gemconvert -d # -d is for "debug"; adds more detailed output to the gemconvert_logfile.txt

Then, paste in the contents of gemconvert_logfile.txt and any output on the screen? Also, what OS are you using, and what do you get from 'python --version'? Are you running this in a conda environment?

**Comment by fkdannemann** [comment]
You are right - it was a Python environment issue.  I got everything working correctly :)

**Comment by ajakef** [comment]
Figured out the likely cause: an incompatible older pandas version (pre-1.3.0). setup.py now specifies pandas>=1.3.0, and pandas will be updated when gemlog is installed/upgraded. To detect future issues like this before they reach users, automated tests now run on "minimal" environments (using old dependency versions) in addition to "bleeding edge" environments (using new dependency versions) so that dependency incompatibilities can be found automatically during development.
