### ISSUE TITLE
PyPI does not have wheels for python 3.10

### ISSUE THREAD

**Issue by kevinsa5** [ajakef/gemlog#31]
The build & deploy workflow is not producing wheels for python 3.10, meaning PyPI has wheels for only 3.7-3.9.  See here: https://pypi.org/project/gemlog/#files

Which python versions are used is decided by `cibuildwheel`, which is currently pinned to version 1.6.3:

https://github.com/ajakef/gemlog/blob/dac709db3f17f012f44e6226c41f797ffef207a6/.github/workflows/build-deploy.yml#L34

Version 1.6.3 is from October 2020, before python 3.10 was released.  The first version to support python 3.10 (non-pre-releases, anyway) was version 2.1.3 from October 2021: https://cibuildwheel.readthedocs.io/en/stable/changelog/

So I suppose the fix is to update the pinned version of `cibuildwheel` to something `>=2.1.3`.  You could unpin it so the latest release is always used, but I sleep better at night when my build systems aren't changing without me telling them to, so I would recommend still keeping a pinned version.  That way things only change when (1) there is a reason to change them and (2) you have the time to evaluate that nothing is broken after the change.

**Comment by ajakef** [comment]
Fixed. Thanks for this info!
