### ISSUE TITLE
verify_huddle_test detrend

### ISSUE THREAD

**Issue by ajakef** [ajakef/gemlog#35]
The waveform figure in gemlog.huddle_test.verify_huddle_test apparently isn't working right (notice the distinct trend in both waveforms below). Need to check to see if there are multiple ways to detrend and if this is the right one. @TLSatterwhite 

![image](https://user-images.githubusercontent.com/3461907/152074494-b16374de-701f-450d-9454-bbb662adb356.png)
[2022-01-23_4_raw.zip](https://github.com/ajakef/gemlog/files/7988262/2022-01-23_4_raw.zip)

**Comment by ajakef** [comment]
Added zip file with raw data.

**Comment by TLSatterwhite** [comment]
Detrend with linear option resolves this issue.
