### ISSUE TITLE
demo zip files may be out of date

### ISSUE THREAD

**Issue by kevinsa5** [ajakef/gemlog#39]
When following the instructions in the first demo and using the zip file, I encountered an error in `gemlog.summarize_gps`:

```python
File ~/miniconda3/envs/gem/lib/python3.10/site-packages/gemlog/gem_network.py:159, in <listcomp>(.0)
    157 header_df = pd.read_csv(station_info, nrows = 1, header = None, index_col = False)
    158 header_list = [header_df[key][0] for key in header_df.keys()]
--> 159 if all([i.lower() in (required_keys + ['elevation']) for i in header_list]): # file has header line
    160     print('File has valid header, using that for column names')
    161     station_info = pd.read_csv(station_info, dtype = {key:'str' for key in header_list}, keep_default_na = False)

AttributeError: 'numpy.int64' object has no attribute 'lower'
```

When I switched to the (non-zipped) directory, the error went away and everything seemed to work as expected.  Based on the modification timestamps I suspect that `demo.zip` file may just be an outdated version of the `demo` directory.  I didn't check the missing_gps demo, but the same might be true there.  

Separately, the `demo_QC` readme references a zip file that doesn't exist.

**Comment by ajakef** [comment]
Thanks for the catch. Fixed in 6ea9e7b207ffa8b9851d5054bf0318310d44908a.
