### ISSUE TITLE
ReadGem_v0_9_single is a bottleneck

### ISSUE THREAD

**Issue by ajakef** [ajakef/gemlog#6]
Despite major speed improvements, this function is still the bottleneck and makes large data conversion projects slow. Consider finding a faster method for reading the text file than pd.read_csv, perhaps a C function.

**Comment by kevinsa5** [comment]
I have a cython-based parser function that appears to give the same results as the pandas-based reader on my test file and is much faster:

```python
%time result_slow = ReadGem_v0_9_single(filename)

CPU times: user 1.24 s, sys: 109 ms, total: 1.35 s
Wall time: 1.35 s

%time result_fast = read_with_cython(filename)

CPU times: user 360 ms, sys: 38.6 ms, total: 398 ms
Wall time: 397 ms
```

No promises it won't segfault on a weird file though... would it be possible to add some tests with the bad files mentioned in #8?  That would give some confidence that it doesn't (or does) crash hard.

**Comment by ajakef** [comment]
Due to major speed improvements by @kevinsa5, this is no longer a top priority. With the move to cython, there is probably less room for improvement. Also, reading the raw data file is less of a bottleneck now: for example, the above comment shows a speed improvement of 3x for the read function specifically, but my tests show only a 2x improvement for the overall conversion workflow due to time spent in other un-sped-up tasks. 

The overall conversion speed for a large amount of data is about 10x in 0.3.0 than in 0.1.1, turning an overnight job into a lunch break job.
